# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2025 SpacemiT Technology Co., Ltd.
#

obj-$(CONFIG_$(PHASE_)ESPI) += espi-uclass.o
obj-$(CONFIG_$(PHASE_)ESPI_SPACEMIT_K3) += espi-spacemit.o espi-spacemit-lib.o
