# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2022-2026 Spacemit, Inc
#
# K3 (X100) boot-media image packaging.
#
# The BROM expects the SPL ("FSBL") wrapped in a Spacemit AIHD image header
# plus a certificate chain, and a small "bootinfo" descriptor that tells the
# BROM the geometry of the boot medium and where the SPL copies live. Both are
# produced by tools/build_binary_file.py from the JSON templates under
# configs/. The signing keys under configs/key/ are the vendor development
# keys shipped in the BSP (not production keys).
#
# Note: unlike the 2022.10 vendor tree, u-boot.itb is generated by binman
# (see arch/riscv/dts/k3-u-boot.dtsi) and already bundles the OpenSBI
# fw_dynamic firmware, U-Boot proper and the control FDT, so no separate
# mkimage .its rule for u-boot.itb (or a standalone fw_dynamic.itb) is needed
# here.

# Wrap spl/u-boot-spl.bin into FSBL.bin (AIHD header + cert chain) and build
# the per-medium bootinfo descriptors.
quiet_cmd_build_spl_platform = BUILD   $2
cmd_build_spl_platform = \
	cp $(srctree)/$3 \
		$(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/ && \
	python3 $(srctree)/tools/build_binary_file.py \
		-c $(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/configs/fsbl.json \
		-o $(srctree)/FSBL.bin; \
	python3 $(srctree)/tools/build_binary_file.py \
		-c $(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/configs/bootinfo_spinor.json \
		-o $(srctree)/bootinfo_spinor.bin; \
	python3 $(srctree)/tools/build_binary_file.py \
		-c $(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/configs/bootinfo_spinand.json \
		-o $(srctree)/bootinfo_spinand.bin; \
	python3 $(srctree)/tools/build_binary_file.py \
		-c $(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/configs/bootinfo_block.json \
		-o $(srctree)/bootinfo_block.bin && \
	rm -f $(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/u-boot-spl.bin

quiet_cmd_build_default_env = BUILD   $2
cmd_build_default_env = \
	$(srctree)/scripts/get_default_envs.sh $(srctree) > $(srctree)/u-boot-env-default.txt && \
	$(srctree)/tools/mkenvimage -s $(CONFIG_ENV_SIZE) -o $(srctree)/u-boot-env-default.bin \
		$(srctree)/u-boot-env-default.txt

MRPROPER_FILES += $(srctree)/board/$(CONFIG_SYS_VENDOR)/$(CONFIG_SYS_BOARD)/u-boot-spl.bin
MRPROPER_FILES += FSBL.bin u-boot-env-default.*
MRPROPER_FILES += bootinfo_spinor.bin bootinfo_spinand.bin bootinfo_block.bin

ifneq ($(CONFIG_SPL_BUILD),)
INPUTS-y += FSBL.bin

FSBL.bin: spl/u-boot-spl.bin FORCE
	$(call if_changed,build_spl_platform,$@,$<)
else
INPUTS-y += u-boot-env-default.bin
u-boot-env-default.bin: u-boot-nodtb.bin FORCE
	$(call if_changed,build_default_env,$@)
endif
